# Generated by Django 2.1.7 on 2019-03-09 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_noticias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='data_hora_criacao',
            new_name='data_criacao',
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='data_hora_publi',
            new_name='data_publi',
        ),
    ]
