# Generated by Django 2.1.7 on 2019-03-09 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_noticias', '0002_auto_20190308_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='data_publi',
            new_name='data_publicacao',
        ),
    ]
